name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    services:
      couchbase:
        image: couchbase/server-sandbox:6.5.0
        ports:
          - 8091-8094:8091-8094
          - 11210:11210

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12']

    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

#      - name: Generate Docs
#        run: npm run docs

#      - name: Build coverage badge
#        run: npm run badge
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: coverage.svg
#          path: coverage/badge.svg
